In [1]:
# 导入数据库
import numpy as np
import pandas as pd

In [2]:
#读入数据
df = pd.read_csv('50-2012-2022.csv')

50

In [20]:
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,600104.SH,20221230,14.42,14.52,14.38,14.41,14.33,0.08,0.5583,120519.68,173895.810
1,600104.SH,20221229,14.56,14.60,14.33,14.33,14.63,-0.30,-2.0506,163599.08,235719.731
2,600104.SH,20221228,14.71,14.74,14.56,14.63,14.76,-0.13,-0.8808,122705.48,179472.449
3,600104.SH,20221227,14.81,14.83,14.65,14.76,14.71,0.05,0.3399,88822.86,130923.419
4,600104.SH,20221226,14.67,14.76,14.63,14.71,14.67,0.04,0.2727,78898.14,116092.604
...,...,...,...,...,...,...,...,...,...,...,...
122913,600030.SH,20120110,9.79,10.25,9.71,10.12,9.75,0.37,3.7900,844565.48,843167.539
122914,600030.SH,20120109,9.36,9.79,9.26,9.75,9.39,0.36,3.8300,623061.16,596959.880
122915,600030.SH,20120106,9.19,9.43,9.04,9.39,9.29,0.10,1.0800,555029.83,513423.431
122916,600030.SH,20120105,9.52,9.72,9.20,9.29,9.56,-0.27,-2.8200,478352.28,453575.472
122917,600030.SH,20120104,9.79,9.85,9.56,9.56,9.71,-0.15,-1.5400,354005.33,343726.604

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df1 = df.iloc[0:3000,5]

In [8]:
df2 = df.loc[1:3000,'close']

In [17]:
#筛选条件数据
df1.min()

11.35

In [10]:
df3 = df[df['close'] == 14.33]
df3

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
1,600104.SH,20221229,14.56,14.60,14.33,14.33,14.63,-0.30,-2.0506,163599.08,2.357197e+05
42,600104.SH,20221102,14.02,14.35,13.96,14.33,14.11,0.22,1.5592,279685.08,3.970514e+05
46,600104.SH,20221027,14.26,14.41,14.21,14.33,14.16,0.17,1.2006,157749.92,2.260634e+05
2220,600104.SH,20131024,13.60,14.68,13.60,14.33,13.60,0.73,5.3700,778251.09,1.112759e+06
9926,600309.SH,20140709,14.74,14.74,14.31,14.33,14.75,-0.42,-2.8500,159211.09,2.307065e+05
10349,600309.SH,20121009,14.25,14.69,14.18,14.33,14.25,0.08,0.5600,242864.35,3.511884e+05
17456,601857.SH,20150428,14.46,15.36,14.05,14.33,14.65,-0.32,-2.1800,8501682.59,1.256177e+07
27115,600703.SH,20190424,13.50,14.69,13.16,14.33,13.50,0.83,6.1481,1398333.21,1.959349e+06
27239,600703.SH,20181022,13.60,14.36,13.60,14.33,13.38,0.95,7.1001,462578.01,6.501714e+05
27650,600703.SH,20170215,14.48,14.79,14.25,14.33,14.52,-0.19,-1.3100,250048.06,3.635198e+05
27655,600703.SH,20170208,14.28,14.36,14.04,14.33,14.25,0.08,0.5600,127226.39,1.806894e+05
27662,600703.SH,20170123,14.35,14.55,14.25,14.33,14.38,-0.05,-0.3500,173870.37,2.492967e+05
33198,600837.SH,20201028,14.20,14.37,14.11,14.33,14.17,0.16,1.1291,344675.12,4.911196e+05
33229,600837.SH,20200907,14.65,14.77,14.33,14.33,14.67,-0.34,-2.3177,578299.25,8.429279e+05
33437,600837.SH,20191101,14.05,14.44,14.01,14.33,14.10,0.23,1.6312,676383.99,9.632249e+05
33905,600837.SH,20171128,14.30,14.36,14.20,14.33,14.34,-0.01,-0.0700,202747.00,2.892908e+05
34368,600837.SH,20160105,13.88,14.70,13.70,14.33,14.28,0.05,0.3500,1099988.04,1.565680e+06
58857,601012.SH,20170208,14.37,14.37,14.17,14.33,14.38,-0.05,-0.3500,110872.75,1.579167e+05
58947,601012.SH,20160919,14.32,14.43,14.15,14.33,14.27,0.06,0.4200,132429.14,1.892439e+05
67044,601989.SH,20150515,14.18,14.78,14.01,14.33,14.16,0.17,1.2000,6484433.55,9.305010e+06
78252,601088.SH,20160707,14.32,14.46,14.25,14.33,14.29,0.04,0.2800,144125.84,2.070218e+05
78375,601088.SH,20160105,14.00,14.56,13.80,14.33,14.15,0.18,1.2700,261572.43,3.697698e+05
78763,601088.SH,20140606,14.38,14.42,14.28,14.33,14.38,-0.05,-0.3500,127642.23,1.832484e+05
78766,601088.SH,20140603,14.31,14.47,14.30,14.33,14.32,0.01,0.0700,59480.13,8.549803e+04
80766,600048.SH,20210415,14.34,14.42,14.25,14.33,14.34,-0.01,-0.0697,311652.60,4.466349e+05
80768,600048.SH,20210413,14.27,14.38,14.12,14.33,14.28,0.05,0.3501,425218.39,6.057647e+05
95816,600585.SH,20140312,14.39,14.52,14.22,14.33,14.45,-0.12,-0.8300,135383.87,1.939999e+05
96190,600585.SH,20120817,14.25,14.43,14.15,14.33,14.29,0.04,0.2800,86644.32,1.237907e+05
110693,601211.SH,20220505,14.39,14.48,14.32,14.33,14.60,-0.27,-1.8493,281799.36,4.052586e+05

In [9]:
df2

1       14.33
2       14.63
3       14.76
4       14.71
5       14.67
        ...
2996    54.01
2997    53.67
2998    53.25
2999    53.11
3000    52.67
Name: close, Length: 3000, dtype: float64